name: DevOps CI/CD Pipeline

on:
  push:
    branches: [ "dev" ] # On écoute uniquement les pushs sur dev

permissions:
  contents: write
  packages: write

jobs:
  pipeline-global:
    name: Validation Dev et Merge Main
    runs-on: ubuntu-latest
    
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1. Qualité Code
      - name: Analyse SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=mohamedkhemaissia
            -Dsonar.projectKey=mohamedkhemaissia_node-bulletin-board
            -Dsonar.projectName=node-bulletin-board
            -Dsonar.sources=bulletin-board-app

      # 2. Sécurité
      - name: Scanner le code avec Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: 'bulletin-board-app'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      # 3. Connexion Docker
      - name: Connexion au Registre GitHub (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Build et Push de l'image (si les étapes 1 et 2 sont OK)
      - name: Build et Push de l'image Docker
        uses: docker/build-push-action@v5
        with:
          context: ./bulletin-board-app
          push: true
          tags: |
            ghcr.io/mohamedkhemaissia/node-bulletin-board:latest

      # 5. Tout est OK ? Le robot merge sur main automatiquement !
      - name: Fusionner automatiquement vers main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git checkout main
          git merge origin/dev --allow-unrelated-histories -m "Automated merge from dev to main"
          git push origin main