name: DevOps CI/CD Pipeline

on:
  push:
    branches: [ "master", "main" ] # Déclenche le pipeline à chaque push

jobs:
  sonarcloud:
    name: Analyse Qualité Code (SonarCloud)
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Analyse SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-docker:
    name: Build Image Docker
    needs: sonarcloud # Attend que SonarCloud valide le code
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4
      - name: Build de l'image
        run: |
          cd bulletin-board-app
          docker build -t bulletin-board:latest .